"use client";

import React, { useEffect, useState } from "react";
import { collection, query, orderBy, limit, getDocs, writeBatch, doc } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { db, functions } from "@/lib/firebase";
import { Sparkles, Check, X, Loader2, Play } from "lucide-react";

export default function AIStagingArea() {
  const [staged, setStaged] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [genSubject, setGenSubject] = useState("english");
  const [genCount, setGenCount] = useState(5);

  const fetchStaged = async () => {
    setLoading(true);
    try {
      const q = query(collection(db, "ai_generated_questions_staging"), orderBy("created_at", "desc"), limit(50));
      const snap = await getDocs(q);
      setStaged(snap.docs.map(d => ({ id: d.id, ...d.data() })));
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchStaged();
  }, []);

  const handleApprove = async (q: any) => {
    try {
      const batch = writeBatch(db);
      
      const newQuestionRef = doc(collection(db, "questions"));
      batch.set(newQuestionRef, {
        subject: q.subject,
        body: q.body,
        text: q.text,
        options: q.options,
        correct_answer: q.correct_answer,
        explanation: q.explanation || "",
        source: "ai",
        approved_at: new Date()
      });

      const stagingRef = doc(db, "ai_generated_questions_staging", q.id);
      batch.delete(stagingRef);

      await batch.commit();

      setStaged(prev => prev.filter(item => item.id !== q.id));
    } catch (err) {
      console.error(err);
      alert("Approve failed.");
    }
  };

  const handleReject = async (id: string) => {
    try {
      const stagingRef = doc(db, "ai_generated_questions_staging", id);
      const batch = writeBatch(db);
      batch.delete(stagingRef);
      await batch.commit();
      
      setStaged(prev => prev.filter(item => item.id !== id));
    } catch (err) {
      console.error(err);
      alert("Reject failed.");
    }
  };

  const generateMore = async () => {
    setGenerating(true);
    try {
      const genFunc = httpsCallable(functions, "generateQuestions");
      await genFunc({ subject: genSubject, count: genCount });
      await fetchStaged();
    } catch (err: any) {
      alert("Generation failed: " + err.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="w-full max-w-7xl">
      <div className="flex flex-col md:flex-row justify-between gap-6 mb-8">
        <div>
          <h1 className="text-3xl font-extrabold text-zinc-900 dark:text-zinc-50 flex items-center gap-3">
            <Sparkles className="text-[var(--brand)]" /> AI Staging
          </h1>
          <p className="text-zinc-500 mt-1">Review and approve questions generated by the AI Engine.</p>
        </div>

        <div className="flex flex-wrap items-center gap-3 p-2 bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-2xl shadow-sm">
          <select 
            value={genSubject} 
            onChange={e => setGenSubject(e.target.value)}
            className="h-10 px-3 border-r border-zinc-200 dark:border-zinc-800 bg-transparent text-sm font-bold uppercase outline-none"
          >
            <option value="english">English</option>
            <option value="maths">Maths</option>
            <option value="physics">Physics</option>
            <option value="chemistry">Chemistry</option>
          </select>
          <select 
            value={genCount} 
            onChange={e => setGenCount(Number(e.target.value))}
            className="h-10 px-3 border-r border-zinc-200 dark:border-zinc-800 bg-transparent text-sm font-bold outline-none"
          >
            {[5, 10, 20].map(n => <option key={n} value={n}>{n} Questions</option>)}
          </select>
          <button 
            onClick={generateMore} 
            disabled={generating}
            className="h-10 px-4 rounded-xl relative overflow-hidden bg-[var(--brand)] text-white font-bold text-sm hover:opacity-90 transition-all flex items-center gap-2 shadow-lg shadow-[var(--brand)]/20 disabled:opacity-50 mx-1"
          >
            {generating ? <Loader2 size={16} className="animate-spin" /> : <Play size={16} />}
            Generate New
          </button>
        </div>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-pulse">
          {[1,2,3,4].map(i => <div key={i} className="h-48 bg-zinc-100 dark:bg-zinc-900 rounded-2xl" />)}
        </div>
      ) : staged.length === 0 ? (
        <div className="text-center py-24 bg-white border border-dashed border-zinc-300 dark:bg-zinc-950 dark:border-zinc-800 rounded-2xl">
          <Sparkles className="mx-auto h-12 w-12 text-zinc-300 dark:text-zinc-700 mb-4" />
          <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-50">Staging Area is Empty</h3>
          <p className="text-zinc-500">Generate more questions using the widget above.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {staged.map((q) => (
            <div key={q.id} className="bg-white border border-zinc-200 rounded-2xl shadow-sm dark:bg-zinc-950 dark:border-zinc-800 flex flex-col hover:border-zinc-300 dark:hover:border-zinc-700 transition-colors">
              <div className="p-6 flex-1">
                <div className="flex gap-2 mb-4">
                  <span className="px-2 py-1 rounded bg-zinc-100 dark:bg-zinc-900 text-[10px] font-black uppercase tracking-widest text-zinc-600 dark:text-zinc-400">
                    {q.subject}
                  </span>
                  <span className="px-2 py-1 rounded bg-[var(--brand)]/10 text-[var(--brand)] text-[10px] font-black uppercase tracking-widest">
                    {q.body}
                  </span>
                </div>
                <p className="font-medium text-zinc-900 dark:text-zinc-50 mb-4">{q.text}</p>
                <div className="flex flex-col gap-2 mb-4">
                  {['a','b','c','d'].map(opt => {
                    const isCorrect = q.correct_answer?.toLowerCase() === opt;
                    return (
                      <div key={opt} className={`px-3 py-2 rounded-lg border text-sm flex gap-3 ${isCorrect ? 'bg-green-50 border-green-200 dark:bg-green-950/30 dark:border-green-900/50' : 'bg-transparent border-zinc-200 dark:border-zinc-800'}`}>
                        <span className={`font-black uppercase ${isCorrect ? 'text-green-600' : 'text-zinc-400'}`}>{opt}.</span>
                        <span className={isCorrect ? 'text-green-900 dark:text-green-100 font-medium' : 'text-zinc-600 dark:text-zinc-400'}>{q.options?.[opt]}</span>
                      </div>
                    );
                  })}
                </div>
                {q.explanation && (
                  <div className="mt-4 p-3 bg-zinc-50 dark:bg-zinc-900/50 rounded-lg text-xs text-zinc-500">
                    <span className="font-bold text-zinc-700 dark:text-zinc-300">Explanation:</span> {q.explanation}
                  </div>
                )}
              </div>
              <div className="p-2 border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-900/50 flex gap-2 rounded-b-2xl">
                <button onClick={() => handleApprove(q)} className="flex-1 h-10 flex items-center justify-center gap-2 rounded-xl bg-green-500 text-white font-bold text-sm hover:bg-green-600 transition-colors shadow-sm shadow-green-500/20">
                  <Check size={16} /> Approve
                </button>
                <button onClick={() => handleReject(q.id)} className="h-10 px-4 flex items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white text-red-500 font-bold text-sm hover:bg-red-50 dark:bg-zinc-950 dark:border-zinc-800 dark:hover:bg-red-950/30 transition-colors shadow-sm">
                  <X size={16} /> Discard
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
